name: Android Tests and apk build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Unit Test + Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Ensure .gradle/caches is empty before writing to it.
        # This helps us stay within Github's cache size limits.
      - name: Clean Cache
        run: rm -rf ~/.gradle/caches

      # Restore the cache.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/app/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/src/main/java/GradleDepenedencies.kt') }}

      # to workaround sdk dir issue on github-actions, using password-less sudo
      - name: Run Unit Tests
        run: sudo ./gradlew test

      - name: Build Debug Apk
        run: sudo ./gradlew assembleDebug
